pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "frontend-app:latest"
        CONTAINER_NAME = "frontend"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'frontend',
                    url: 'https://lab.ssafy.com/s12-webmobile1-sub1/S12P11E203.git',
                    credentialsId: 'songhun-gitlab'
            }
        }

        stage('Check Node Version') {
            steps {
                // Node.js가 설치되어 있는지 확인
                sh 'npm --version'  // npm 버전 출력
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend/aqoo-fe') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Build D
